### ISSUE TITLE
openvpn

### ISSUE THREAD

**Issue by GRajin** [termux/termux-root-packages#123]
**Package description**
Describe what this package do and why it should be available. => It's a VPN package.

**Link to home page and sources**
1. Home page: https://openvpn.net/
2. Source code: https://github.com/OpenVPN/openvpn

**Additional information**
Have you compiled or tried to compile the package on device? => No
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment]
> would be better than using a app.

Won't be better because of messing with Android's routing tables.
Android takes care about routing tables on it's own and doesn't expect that something will modify them outside of API.

**Comment by Grimler91** [comment]
@GRajin it is possible to control the openvpn connection from the command line with `am` as described for example here: https://github.com/schwabe/ics-openvpn/issues/597. I'm reluctant to add it as a package as I don't want to get bug reports that the package doesn't work, when the actual problem is that the user hasn't routed the traffic correctly
