### ISSUE TITLE
Fresh install of dirmngr installs gnupg2

### ISSUE THREAD

**Issue by JamesHagerman** [termux/termux-root-packages#32]
On a fresh install of Termux at least, I was unable to install the key using the command in the readme even though gnupg2 is installed as a dependency for dirmgr. As was mentioned somewhere in this repo, changing the `--recv` to `--recv-keys` worked.

I'm not positive I'm doing everything right but it was a little confusing Can someone double check this?

Thanks!

**Comment by Grimler91** [comment]
Probably because gnupg (version 1) is installed, and apt-key is using it instead of gnupg2. 

We really should remove gnupg from the main repo. I'll look into it, thanks.

**Comment by Grimler91** [comment]
Should be fixed now that gnupg is removed (and gnupg2 is renamed to gnupg). Thanks for reporting!

**Comment by shaheem007** [comment]
im using arm
pkg install gnupg
Ign:1 https://hax4us.github.io/termux-tools termux InRelease
Get:2 https://hax4us.github.io/termux-tools extras InRelease [5670 B]
Ign:3 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Get:4 https://hax4us.github.io/termux-x x11-stable InRelease [5679 B]
Ign:5 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:6 https://hax4us.github.io/termux-tools termux Release
Ign:7 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable InRelease
Get:8 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Ign:9 https://hax4us.github.io/termux-tools termux/extras arm Packages
Get:10 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:10 https://dl.bintray.com/grimler/science-packages-24 science Release
Ign:11 https://hax4us.github.io/termux-tools termux/extras all Packages
Ign:2 https://hax4us.github.io/termux-tools extras InRelease
Ign:9 https://hax4us.github.io/termux-tools termux/extras arm Packages
Get:12 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release [6065 B]
Ign:11 https://hax4us.github.io/termux-tools termux/extras all Packages
Get:13 https://dl.bintray.com/grimler/game-packages-24 games Release.gpg [475 B]
Get:14 https://hax4us.github.io/termux-tools extras/main all Packages [964 B]
Get:15 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release.gpg [821 B]
Err:4 https://hax4us.github.io/termux-x x11-stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A13A121F25D06F7
Get:16 https://hax4us.github.io/termux-tools extras/main arm Packages [2076 B]
Ign:9 https://hax4us.github.io/termux-tools termux/extras arm Packages
Ign:11 https://hax4us.github.io/termux-tools termux/extras all Packages
Err:9 https://hax4us.github.io/termux-tools termux/extras arm Packages
  404
Ign:11 https://hax4us.github.io/termux-tools termux/extras all Packages
Get:18 https://dl.bintray.com/grimler/game-packages-24 games/stable arm Packages [2992 B]
Get:19 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main arm Packages [16.9 kB]
Reading package lists... Done
W: GPG error: https://hax4us.github.io/termux-tools extras InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A13A121F25D06F7
W: GPG error: https://hax4us.github.io/termux-x x11-stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A13A121F25D06F7
E: The repository 'https://hax4us.github.io/termux-x x11-stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
