### ISSUE TITLE
Package request: sshfs

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-root-packages#45]
If sshfs or similar tools are available in termux, than we could use both linux/android tools to develop on the hard drive.
For example, we can compile java to jar on PC, and then use termux's dx and aapt to package android app without copying back and forth.

$ pacman -Si sshfs
Repository      : community
Name            : sshfs
Version         : 2.7-1
Description     : FUSE client based on the SSH File Transfer Protocol
Architecture    : x86_64
URL             : http://github.com/libfuse/sshfs
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : fuse  glib2  openssh
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 31.61 KiB
Installed Size  : 76.00 KiB
Packager        : Antonio Rojas arojas@archlinux.org
Build Date      : Fri 22 Apr 2016 03:28:39 AM CST
Validated By    : MD5 Sum  SHA-256 Sum  Signature

**Comment by husnoo** [comment]
Does anybody have a working libfuse.deb I could try on aarch64? Just wondered if somebody got it working before I mess with building termux packages myself. I'm hoping to run fusepy on Android 7.0.

**Comment by rodajc** [comment]
Yes please. Can't wait for the sshfs package!

**Comment by ZaxonXP** [comment]
@rodajc : Mee too. :)

**Comment by ldmosquera** [comment]
me three!

**Comment by petrich** [comment]
yes, here also.

**Comment by Gitkubikon** [comment]
Yes, I do as well 👌

**Comment by neiviv-ui** [comment]
Hi, I have made sshfs working on termux (with rooted phone), you just need to download and run this install.sh I have made (who compile and install dependencies for sshfs)
In Termux :
`git clone https://github.com/neiviv-ui/termux-sshfs`
`cp termux-sshfs/install.sh $HOME/install.sh`
`chmod +x install.sh`
`./install.sh`

If you have LINE_MAX error, uncomment the corresponding line in install.sh

When it will have finished, you should have a sshfs script at $HOME.

Run `su`, and add /data/data/com.termux/files/usr/bin to your $PATH
`export PATH=/data/data/com.termux/files/usr/bin:$PATH`
(If you don't want to do this everytime, modify /data/data/com.termux/files/usr/bin/su and add /data/data/com.termux/files/usr/bin: at the PATH line)

You can know simply run `./sshfs  [user@]hostname:[directory] mountpoint`
If you want to be able to modify the files as simple termux user, run `./sshfs  [user@]hostname:[directory] mountpoint -o allow_other`

**Comment by rodajc** [comment]
E: Unable to locate package libfuse3
./install.sh: 49: ./install.sh: python: not found
./install.sh: 50: ./install.sh: pip: not found

**Comment by neiviv-ui** [comment]
Yes, I Know,
I need to adapt it to be a package and not just an install script
But thanks for answer ;-)

**Comment by neiviv-ui** [comment]
> E: Unable to locate package libfuse3
> ./install.sh: 49: ./install.sh: python: not found
> ./install.sh: 50: ./install.sh: pip: not found


I have corrected that, just download again the install.sh
;-)
Bye

**Comment by Tony-il-Capo** [comment]
@neiviv-ui many thanks, your script ran without any errors and preliminary tests shows that sshfs seems to be working.

I didn't test much though, just mounted server with key - ok; ls /mountpoint - files were there, and also unmounted successfully.

I needed to use -F /data/data/com.termux/files/home/.ssh/config for loading SSH configuration file already set in termux

Will test more and report.
Thanks again

**Comment by Tony-il-Capo** [comment]
Hi
The problem I have with SSHFS is that I can't make the mount avaiable to other apps, especially to File Explorers/Browsers.

I tried the options uid, gid with 9997 (user 'everybody') and allow_other with no success. Also tried the 'mount master' -M/--mm option for su, nothing exposes mount to other apps. Created a test folder in /sdcard and then mounted, but Ghost Commander sees folder empty, while executing ls in terminal lists all files.

The only thing that works is creating a test folder inside /system/ and then use Ghost Commander in root browser mode, this way I can see files there, but it only lets me copy them to device storage.

I think for my case an NFS implmentation would work better, but can't find anything about it and getting fuse to work with NFS.
I wanted to access mostly media files and play directly from source, without need to copy them. Also, I need to be able to stream, simple HTTP streaming don't do. There's little to no apps that support NFS.

**Comment by Dmole** [comment]
Android has that  Storage Access Framework (SAF) that fails to sync with the underlying file system without a reboot. This can cause issues with Ghost Commander and other apps just moving files without even mounting. I find com.github.axet.filemanager works best.

**Comment by neiviv-ui** [comment]
Hi
For me (to see files throught an explorer), I used an explorer which has the option "connect to a storage", for example fx, added "termux storage", and this way i could see, edit, and run my files in android (of course you need the option -o allow_other to make this work).

Link to fx : https://play.google.com/store/apps/details?id=nextapp.fx

Bye

**Comment by Tony-il-Capo** [comment]
It's that SAF thing @Dmole mentioned. I installed [com.github.axet.filemanager](https://f-droid.org/en/packages/com.github.axet.filemanager/) and I can access via SAF source, the SSHFS mounts inside termux folder ...files/home/
Termux creates that shared storage. 

I can see and edit text files (inside the mentioned file manager), but if I want to open some media files, the media player apps reject the files, because it seems they don't support  SAF. Some File Browser with some kind of intermediate proxy between storage and external app should work.

**Comment by neiviv-ui** [comment]
> 
> 
> It's that SAF thing @Dmole mentioned. I installed [com.github.axet.filemanager](https://f-droid.org/en/packages/com.github.axet.filemanager/) and I can access via SAF source, the SSHFS mounts inside termux folder ...files/home/
> Termux creates that shared storage.
> 
> I can see and edit text files (inside the mentioned file manager), but if I want to open some media files, the media player apps reject the files, because it seems they don't support SAF. Some File Browser with some kind of intermediate proxy between storage and external app should work.

Sorry, I haden't correctly read.

**Comment by Tony-il-Capo** [comment]
> I can see and edit text files (inside the mentioned file manager), but if I want to open some media files, the media player apps reject the files, because it seems they don't support SAF. Some File Browser with some kind of intermediate proxy between storage and external app should work.

**UPDATE:**
**Found the solution,** installed another File Explorer named _[Material Files](https://f-droid.org/en/packages/me.zhanghai.android.files/)_

This one works great, after adding the Termux shared storage (SAF) in "_Material Files_" explorer,  now I can open files with external apps, I'm able toplay media files with external players and I'm even able to seek media (jump to desired time), I was not sure I could do it with sshfs because of sftp limitations.

**Comment by neiviv-ui** [comment]
#https://github.com/neiviv-ui/termux-sshfs/issues/1

**Comment by Tony-il-Capo** [comment]
**OFF TOPIC:**

Hi @neiviv-ui any change of doing the crosscompile also for [fuse-nfs](https://github.com/sahlberg/fuse-nfs)?

SSHFS works great when using internet (WAN), because connection speed is most of the times slower than the speed SFTP/SSHFS connections can reach anyway, but is much slower than NFS  would be in LAN.
For example, I've been using [NFS client for windows](https://github.com/billziss-gh/nfs-win) OS, instead of SSHFS, also available for Windows, because in LAN connections SSHFS is so much slower than NFS and in LAN we don't need encryption.

**Comment by neiviv-ui** [comment]
Hi,
I haven't thought about it as I only wanted to use it on WAN, but if by crosscompile you meant recompiling it in termux, I don't know if I'm able to.
Also, check out this :
https://gist.github.com/aldur/4a3f90a111b71662f056
It may be what you need.
In all case I will check it out and try ;-)

**Comment by Tony-il-Capo** [comment]
Hi, thanks for your time

Yes, I meant recompiling it in Termux, I thought of this because I saw libnfs and libfuse available in Termux packages, but there's more libs needed...

Unfortunately, none of those solutions work for me.
I tried them already some time ago, mounting with Busybox command need NFS module, absent from my devices (tried it in Galaxy A40/Android 9 and also old 4.1 on my Xperia S), also, can't find any compiled module compatible with kernel...

NetworkBrowser app, last time I've tried it, there was no support for NFS, only Samba, as we can read in description.

> Presently, Network Browser should be able to connect to most Microsoft Windows or Linux and Mac OSX smb **samba network shared folders**

Having to install samba on my Linux servers is not a good solution for me, as NFS is native to Linux, and most of my systems run Linux, so I can connect ok between them, even when using Windows I can access shares with nfs-win (FUSE), but never found anything that worked for Android.

I think I will stick with sshfs then, as it is working really great for me, the only thing to point is the speed disadvantage in LAN connections, but anyway, many thanks again for making it available for Termux/Android.

**Comment by neiviv-ui** [comment]
After all,
I think I will do it, I will post it when it will be finished😉.
I may make topic for it.

**Comment by FreddieOliveira** [comment]
## Package description

SSHFS allows you to mount a remote filesystem using SFTP locally in the client machine using FUSE, instead of simply remotely connecting to it with `ssh`. This can be used to facilitate file copying between the host and client, discarding the use of `scp`, for example.

SSHFS is written and maintained by the FUSE devs.

Here's the Ubuntu package page for reference:
https://packages.ubuntu.com/groovy/sshfs

## Link to home page and sources

1. Home page: https://github.com/libfuse/sshfs
2. Source code: https://github.com/libfuse/sshfs

## Additional information

### Dependencies

These are the libs it depends upon:

```
libfuse3.so
libc.so
libglib-2.0.so
```

It also depends on `rst2man.py` in order to build the man page, which can be installed by `pip3 install docutils`

### Build instructions

All the steps above were executed from within termux using the latest stable version (v. 3.7.1) of SSHFS. First download the patches, then run:

```
$ wget https://github.com/libfuse/sshfs/releases/download/sshfs-3.7.1/sshfs-3.7.1.tar.xz
$ tar xf sshfs-3.7.1.tar.xz && cd sshfs-3.7.1
$ patch meson.build ../meson.build.patch
$ patch sshfs.c ../sshfs.c.patch
$ mkdir build && cd build
$ meson -D sbindir=bin -D buildtype=release -D strip=true -D prefix=$PREFIX ..
$ ninja install
```

This is the list of files added to the system when installed:

```
files
└── [105K]  usr
    ├── [76K]  bin
    │   ├── [18]  mount.fuse.sshfs -> sshfs
    │   ├── [18]  mount.sshfs -> sshfs
    │   └── [72K]  sshfs
    └── [25K]  share
        └── [21K]  man
            └── [17K]  man1
                └── [13K]  sshfs.1

 109K used in 5 directories, 4 files
```

Running the test suit fails with permission denied even running as root. This isn't actually a real problem and has already been seen when [testing libfuse3.](https://github.com/termux/termux-root-packages/issues/189)

From my practical tests everything seems to be working correctly with one caveat: *one must become root with `su` before running the sshfs command; prepending `sudo` or becoming root with `tsu` mysteriously doesn't work, it seems to be some kind of limitation of the sudo script.* Further analysis is needed here.

@xeffyr @Grimler91 @cswl any idea what this sudo problem might be?

## Attachments

[meson.build.patch.txt](https://github.com/termux/termux-root-packages/files/5762347/meson.build.patch.txt)
[sshfs.c.patch.txt](https://github.com/termux/termux-root-packages/files/5762349/sshfs.c.patch.txt)

**Comment by xeffyr** [comment]
> any idea what this sudo problem might be?

From how you described the issue it looks very similar to *Samsung rooting restriction* which limits root abilities for the `fork()`'ed processes. This also could be a problem with your `su` (Magisk?).

**Comment by FreddieOliveira** [comment]
> limits root abilities for the fork()'ed processes.

Hmm, it sounds plausible. But it's strange that even using root very often, this is the very first time I have this kind of problem.

> This also could be a problem with your su (Magisk?).

This might be possible, but I'm not sure. Magisk already proved to have some bugs, like only offering only 32 bit executables, which caused issue #191. In any case, I only have one device, so I can't check on that.

**Comment by ayoubelmhamdi** [comment]
now , you must install some distribution in termux (debian /arch/void....) 
then you can install sshfs in new distribution
exit from new distribution
in termux home ,you can see folder 'void-fs' in this folder you have your new distribution
you can write some scripte to mouve all file frome new distribution to your termux

**Comment by f3mo** [comment]
It's been 5 years. Wow.

**Comment by SudoNova** [comment]
Hello?

**Comment by petrich** [comment]
is sshfs done?

**Comment by Grimler91** [comment]
@petrich no, no one has spent time trying to cross-compile it for termux as far as I know. 
@FreddieOliveira's instructions above probably still work for compilation on device.

**Comment by Grimler91** [comment]
Building sshfs is [rather trivial](https://github.com/termux/termux-root-packages/commit/030a439e718b0352ae8ad193adeaebd5c3302363), but using it is a bit wonky. As for @FreddieOliveira it seem to only work if run from a tsu shell (and not with sudo), with magisk. It also fails to unmount the mountpoint automatically on exit, instead it just hangs, so unmounting has to be done manually from another shell

**Comment by ippocratis** [comment]
> Hi, I have made sshfs working on termux (with rooted phone), you just need to download and run this install.sh I have made (which compiles and installs dependencies for sshfs). Requirement : Rooted phone Termux (classic version, not legacy) In Termux : `git clone `[`https://github.com/neiviv-ui/termux-sshfs`](https://github.com/neiviv-ui/termux-sshfs) `cp termux-sshfs/install.sh $HOME/install.sh` `chmod +x install.sh` `./install.sh`
> 
> When it will have finished, you should have a sshfs script at $HOME (or at `/data/data/com.termux/files/usr/bin/` if you have chosen the option)
> 
> Run `su`, and add /data/data/com.termux/files/usr/bin to your $PATH `export PATH=/data/data/com.termux/files/usr/bin:$PATH` (If you don't want to do this everytime, modify `/data/data/com.termux/files/usr/bin/su` and add `/data/data/com.termux/files/usr/bin:` at the `PATH` line)
> 
> You can know simply run (`./`)`sshfs [user@]hostname:[directory] mountpoint` If you want to be able to modify the files as simple termux user, run (`./`)`sshfs [user@]hostname:[directory] mountpoint -o allow_other`
> 
> edit : If you have authorization problems, then copy sshfs to /system, it should work. Be careful, you can have wi-fi problems if you don't correctly execute : `fusermount -u mountpoint` or `fusermount3 -u mountpoint`
> 
> DO IT AT YOUR OWN RISKS

Thanks for this
I can Mount a remote with sshfs and I can list its contents with ```ls``` but the android file managers wont show any contents
any idea why or any workaround?
Thanks

**Comment by sierratango88** [comment]
@Grimler91 thank you for creating the package. I can confirm `sshfs` also works with the Dropbear client. Is it possible to make the dependency requirement be either `openssh` or `dropbear`?
