### ISSUE TITLE
Package request: Docker engine

### ISSUE THREAD

**Issue by danielmeneses** [termux/termux-root-packages#60]
Great job for all that Termux is. I know that this is probably a "no can do", but would be a for a nobel award!

;)

**Comment by xeffyr** [comment]
Found on Github termux-packages fork with containers-related stuff:
https://github.com/ContainerDroid/termux-packages/blob/master/packages/docker/build.sh

Though, require custom kernel anyway.

**Comment by FreddieOliveira** [comment]
> Found on Github termux-packages fork with containers-related stuff:
> https://github.com/ContainerDroid/termux-packages/blob/master/packages/docker/build.sh
> 
> Though, require custom kernel anyway.

I tried this, but every container I `docker run` gives me `no matching manifest for android/arm64 in the manifest list entries`, which is expected, since Android is not officialy supported by the images.

![Screenshot_20200531-203509_Termux](https://user-images.githubusercontent.com/9597536/83365923-57695280-a39b-11ea-83c8-39cf3f131afd.png)

So I passed the `--platform=linux/arm64` to pull and run the Linux version of the image, but this docker version is too old and don't support this flag. So, I built the most recent version of docker and tried again, receiving the error `operating system is not supported`.

![Screenshot_20200531-211606_Termux](https://user-images.githubusercontent.com/9597536/83366227-2a1da400-a39d-11ea-9bd1-fdddc2426d69.png)

This error means that the host OS can't run the requested container. I didn't agree that Android can't run Linux containers, so I patched the code to ignore the error and continue anyway, which finally gave me a segmentation fault (ノ°益°)ノ

![Screenshot_20200531-211226_Termux](https://user-images.githubusercontent.com/9597536/83366135-aa8fd500-a39c-11ea-9d69-b818fb14fb83.png)

I'm still not sure why exactly and at which function it segfaults, and no lucky on running any container in termux without prooting a Linux OS yet (｡•́︿•̀｡)

**Comment by xeffyr** [comment]
It was not able to setup image layers. This is not possible if AUFS, OverlayFS or BTRFS support was not compiled into your kernel - that's not only thing missing in Android kernel. You need full support for namespaces and cgroups. And if you want networking, then VETH will be needed too.

Docker is much more complex than simple chroot. Linux kernel used by Android OS has only bare minimum of the features and doesn't meet the requirements of Docker.

**Comment by xeffyr** [comment]
Termux-root-packages has `lxc` which you may want to try. But it still requires cgroups, like Docker.

**Comment by FreddieOliveira** [comment]
Actually it is using overlay2

![Screenshot_20200531-220726_Termux_1](https://user-images.githubusercontent.com/9597536/83367529-8801ba00-a3a4-11ea-8b8d-3085c5819aa7.png)

I enabled OverlayFS when compiling the kernel. I think I enabled everything that's necessary, here's the [check-config.sh](https://github.com/moby/moby/blob/master/contrib/check-config.sh) output for reference:

![IMG_20200531_215841](https://user-images.githubusercontent.com/9597536/83367311-6b18b700-a3a3-11ea-9cce-b0aafebf27ed.jpg)

> Termux-root-packages has lxc which you may want to try. But it still requires cgroups, like Docker.
 
I'll give it a shot

**Comment by FreddieOliveira** [comment]
@xeffyr I'm getting the following error:

![Screenshot_20200601-020330_Termux](https://user-images.githubusercontent.com/9597536/83377607-9ad8b680-a3c5-11ea-8847-310edca2b275.png)

From what I checked in the source code, it's comparing  `/dev/cg2_bpf` with `/sys/fs/cgroup/` and returning the error since they aren't equal. Note that `/sys/fs/cgroup` exists in my system and that I'm running this commands from pure termux (didn't use chroot, nor termux-chroot, etc). Also my kernel misses the pidfds. I can fix that,  but not sure if that's the real error cause.

Here's the `lxc-checkconfig` output 

![Screenshot_20200601-020458_Termux](https://user-images.githubusercontent.com/9597536/83377915-9b258180-a3c6-11ea-95dd-ba18e4ce9c24.png)

Am I doing smt wrong?

**Comment by FreddieOliveira** [comment]
> Also my kernel misses the pidfds. I can fix that

No, I can't. Just researched about and `pidfd_send_signal` was introduced in only in kernel 5.1. My phone runs kernel 4.4 and as far as I know, no Android phone runs a kernel greater than 4.9.

**Comment by xeffyr** [comment]
@FreddieOliveira Then I can revert it back to version I have working on my device with 3.18 kernel. I didn't tested the latest one as I no longer use root & custom kernel/rom anymore.

**Comment by FreddieOliveira** [comment]
Cool. The pidfds no longer is a issue. But I still get the first error:

![Screenshot_20200601-134412_Termux](https://user-images.githubusercontent.com/9597536/83431783-6a296900-a427-11ea-973d-67b225c12a4a.png)

Which is strange because checking the log we can see that it knows that the cgroup is under `/dev/cg2_bpf` instead of  `/sys/fs/cgroup`, but it still try to access the wrong path:

![Screenshot_20200601-134434_Termux](https://user-images.githubusercontent.com/9597536/83432182-06537000-a428-11ea-8ca8-d82b190d05a3.png)

I'll play with the source code to see what I can do about it

**Comment by xeffyr** [comment]
I have provided a script `lxc-setup-cgroups` which will properly setup mounts under /sys/fs/cgroup.
You have `/dev/cg2_bpf` which I don't have. I've used only cgroups v1, so I can't be sure if it compatible with cgroups v2 on Android.

Maybe LXC will require additional patches.

**Comment by map220v** [comment]
@FreddieOliveira Try `sudo umount /dev/cg2_bpf` it's worked for me.

Also i got error : Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
Fixed by this commands :
```
sudo mkdir -p /sys/fs/cgroup/systemd
sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
```

**Comment by FreddieOliveira** [comment]
Thanks for the tips and good to know there's someone with custom kernel to test things out. Actually, I've already successfully ran lxc for quite a while. I ended up having to compile it from source, since some patches applied were not working for me: e.g. my phone creates cpuset.cpus and cpuset.mem inside the cgroup hierarchy, so I had to compile without those patches.

![2020_06_08_023451](https://user-images.githubusercontent.com/9597536/83995859-0f719f00-a94a-11ea-8dcc-24cd2f2a0d2e.png)l

Also [Android 10](https://source.android.com/devices/tech/perf/cgroups) features an auto cgroup setup upon boot via the `cgroup.json` file. The idea behind it is good and it'd replace the `lxc` script in case it worked. But, unfortunately it can't mount the cgroup inside `/sys/fs/cgroup` by itself, since this folder has very restricted permissions and should be mounted as tmpfs before setting cgroups inside it. So, the json file is actually useless in this case, because it can't setup things at the standard `/sys/fs/cgroup` dir. I deleted it, and wrote a very similar script to @xeffyr `lxc-setup-cgroups` one to setup things manually.

What I still wasn't able to accomplish is to run a Linux container. The [lxc templates](https://github.com/lxc/lxc-templates) are old and very buggy, I'm still patching the Ubuntu's one. Were you able to run any Linux container?

My idea is to try to run docker from inside an lxc container. Or maybe, just bootstrap a Linux, chroot inside it and try to run Docker from there. @xeffyr , have you ever tried any of that?

**Comment by xeffyr** [comment]
> Were you able to run any Linux container?

Ubuntu worked for me.

> Or maybe, just bootstrap a Linux, chroot inside it and try to run Docker from there. @xeffyr , have you ever tried any of that?

@FreddieOliveira Yes, Docker works under chroot. You can go with something like http://dl-cdn.alpinelinux.org/alpine/v3.12/releases/aarch64/alpine-minirootfs-3.12.0-aarch64.tar.gz as base for Docker installation.

**Comment by FreddieOliveira** [comment]
> Yes, Docker works under chroot. You can go with something like http://dl-cdn.alpinelinux.org/alpine/v3.12/releases/aarch64/alpine-minirootfs-3.12.0-aarch64.tar.gz as base for Docker installation.

Indeed, I was able to run docker inside a chrooted rootfs of alpine and ubuntu. Things were a bit unstable and my phone often reboots after running the containers (not sure if it's my kernel, or whatever), but it works.

Another option for who's interested, is to emulate a GNU/Linux distro using qemu and run docker inside the VM. This has the advantage of not needing a rooted device nor a custom kernel. But as it's been running under an emulated environment, it will be slower than running the chrooted alternative.

Those are the only two ways of running docker containers under Android, as far as I'm concerned.

**Comment by FreddieOliveira** [comment]
@xeffyr I noted that the kernel, by default, indeed creates the cgroups hierarchy with the `cpuset` prefix, but the Android, while booting, renames the files by striping the prefix, thus changing `cpuset.cpus` and `cpuset.mems` to just `cpus` and `mems` (among others files).

In Android versions bellow 10, this happens when the init process is executing the `/init.rc` script. If desired, one can edit this script to prevent the renaming and even to automate the cgroup mounting under the default `/sys/fs/cgroup` dir.

In Android 10, things were changed and the init process creates the cgroups by itself, using the `cgroups.json` just to check the mount location and the `/init.rc` to do some additional setups. So, to prevent the renaming, one should patch the Android source code and compile it, or simply delete the `cgroups.json` file, so the Android won't even try to setup cgroups. After the phone boots it's still necessary to mount cgroups manually.

**Comment by xeffyr** [comment]
> my phone often reboots after running the containers

I had same and that was caused by null pointer dereference in xt_qtaguid subsystem which is Android specific. That bug exists for a long time and I'm not sure if it was fixed in Android 10.

I patched it manually, that broke its functionality but Docker ran perfectly after that.

**Comment by xeffyr** [comment]
And here is an applied patch:
``` .diff
--- orig/net/netfilter/xt_qtaguid.c     2020-05-12 12:13:14.000000000 +0300
+++ my/net/netfilter/xt_qtaguid.c       2019-09-15 23:56:45.000000000 +0300
@@ -737,7 +737,7 @@
 {
        struct proc_iface_stat_fmt_info *p = m->private;
        struct iface_stat *iface_entry;
-       struct rtnl_link_stats64 dev_stats, *stats;
+       struct rtnl_link_stats64 *stats;
        struct rtnl_link_stats64 no_dev_stats = {0};


@@ -745,13 +745,8 @@
                 current->pid, current->tgid, from_kuid(&init_user_ns, current_fsuid()));

        iface_entry = list_entry(v, struct iface_stat, list);
+       stats = &no_dev_stats;

-       if (iface_entry->active) {
-               stats = dev_get_stats(iface_entry->net_dev,
-                                     &dev_stats);
-       } else {
-               stats = &no_dev_stats;
-       }
        /*
         * If the meaning of the data changes, then update the fmtX
         * string.
```

**Comment by FreddieOliveira** [comment]
> That bug exists for a long time and I'm not sure if it was fixed in Android 10

I can confirm this bug is still present in Android 10. The source code is exactly the same and applying your patch solves the problem! Thanks for sharing the patch, btw 👍 I would've spent days figuring it out by myself.

**Comment by FreddieOliveira** [comment]
Finally, it worked!

![2020_06_17_125704](https://user-images.githubusercontent.com/9597536/84854348-f0ad8f80-b050-11ea-8c59-926a474378ad.png)

This is docker successfully running containers directly in Android. No chroot inside GNU/Linux rootfs and no VM emulation with qemu. This is pure Android.

As showed [here](https://github.com/termux/termux-root-packages/issues/60#issuecomment-636553841), docker runs fine in Android, it just can't pull any container since the Android OS isn't supported by them. Trying to politely ask a Linux version of the container with the flag `--platform=linux` didn't work either. So I lost my patience debugging the seg fault I was getting and had the idea to spoof my operating system by replacing every occurrence of `runtime.GOOS` (which returns the string android) by `"linux"`. And guess what, it worked.

I opened a feature request in docker repo yesterday: https://github.com/moby/moby/issues/41111, but I'm not sure if they'll take it seriously.

**Comment by SDRausty** [comment]
@danielmeneses there is an alternative to docker that runs in Termux PRoot.  It is called udocker: https://www.google.com/search?q=TermuxArch+udocker

**Comment by mmBesar** [comment]
Docker on android would be great

**Comment by FreddieOliveira** [comment]
For whoever is interested in get docker running on its phone, I've written a step by step [gist](https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27)

After 7 months using it I can say it's working pretty stable on my phone. The only thing I couldn't get working 100% is the network isolation for the containers. For now, to give the containers internet access you have to expose its network by using the `--net=host` flag.

@xeffyr @Grimler91 A PR for docker in termux-unstable would be accepted?

**Comment by xeffyr** [comment]
@FreddieOliveira Yes, PR would be nice.

As for networking, I guess here is something to do with Android firewall or routing tables, if relevant drivers are already enabled.

**Comment by FreddieOliveira** [comment]
> if relevant drivers are already enabled

I believe they are.

> As for networking, I guess here is something to do with Android firewall or routing tables

That's what I think. Since I use AdAway and AFWall+ apps, my routing table is pretty messed up. Probably it's something silly I haven't figured out yet. When the PRs are done, I'll open an issue specific for this internet problem, so this issue here can be closed and the relevant discussion continues there.

**Comment by FreddieOliveira** [comment]
> I'll open an issue specific for this internet problem

This isn't needed anymore. The problem was already [solved](https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27#311-internet-access) and was indeed related with the routing table.

**Comment by FreddieOliveira** [comment]
It took almost 5 years since this issue was opened, but Docker is finally part of the root repo. Run `pkg install docker` to install it.

*Note that you still need a compatible kernel to run it.*

**Comment by softyn** [comment]
Could you describe how to install and what are final requirements? I downloaded termux on my (non rooted) android device, run 'pkg install docker' and got 'unable to locate package docker' :(

**Comment by FreddieOliveira** [comment]
Unfortunately you won't be able to run docker (or any program from termux-root repository) on non-rooted devices. You need to root your phone, compile your kernel with the necessary features, subscribe to termux-root repo with `pkg install root-repo` and install docker with `pkg install docker`. Only then you'll be able to run it.

**Comment by thebestnom** [comment]
I get `mount: bad /etc/fstab: No such file or directory` what do you meant by relevant kernel features?

**Comment by xy815661276** [comment]
We open the Android container, which can run the docker container on the Android operating system. Not only can run Docker containers, but also other containers, such as podman. In addition, we have also enabled the container to support checkpoint and restore functions, and support the migration of containers across architectures and operating systems. See https://github.com/xy815661276/Android-Container for details.

**Comment by Grimler91** [comment]
Closing since docker is available for several months already
